version: '3.7'
services:
    db:
        build:
            ./backend
        container_name: container-mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./backend/data:/var/lib/mysql

    