version: '3.7'
services:
    banco:
        image: mysql
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
    